<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('More Information') ?></caption>
            <tbody>
            <?php foreach ($_additional as $_data): ?>
                <tr>
                    <th class="col label" scope="row"><?php echo $block->escapeHtml(__($_data['label'])) ?></th>
                    <td class="col data" data-th="<?php echo $block->escapeHtml(__($_data['label'])) ?>"><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                </tr>
            <?php endforeach;
			// Added Categories breadcrumbs to attributes listing - RobGT 02/06/17
			?>
			
			<tr>
				<th class="label">Category</th>
				<td class="data">
					<ul>
					<?php
					$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
					$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
					
					$productId = $block->getProduct()->getId();
					$product = $productRepository->getById($productId);
					
					$categoryIdArray = $product->getCategoryIds();
					$categoryIds = (!empty($categoryIdArray) ? $categoryIdArray : 0);
					$categoryCollection = $categoryCollection->create()
                                     ->addAttributeToSelect('*')
                                     ->addAttributeToFilter('entity_id', $categoryIds);
									 
						// if the product is associated with any category
						if ($categoryCollection->count()) {
						?>
						<?php
							foreach($categoryCollection as $cat){
								$parents = $cat->getParentCategories();
								?>
								<li>
								<?php
								$catSeparator = '';
								foreach ($parents as $parentCat) {
									// Build the parent links
									$parentCatName = $parentCat->getName();
									if ($parentCatName!='root-catalog' && $parentCatName!='Default Category' && $parentCatName!='Oversized' && $parentCatName!='Dangerous Goods') {
									?>
									<?php echo $catSeparator; ?>
									<a href="<?php echo $parentCat->getUrl(); ?>">
										<?php echo $parentCatName; ?>
									</a>
									<?php
									$catSeparator = '&nbsp;&raquo;&nbsp;';
									}
								}
								?>
								</li>
							<?php
							}
						} else { ?>
						
							<li>Not Categorised</li>
						
						<?php
						}
						?>
					</ul>
				</td>
			</tr>
			
            </tbody>
        </table>
    </div>
<?php endif;?>
